//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingGirl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishingGirl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an ancient.
        /// </summary>
        internal static string Ancient {
            get {
                return ResourceManager.GetString("Ancient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong Arm.
        /// </summary>
        internal static string BadgeBronzeCast {
            get {
                return ResourceManager.GetString("BadgeBronzeCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast {0} metres with the bronze rod..
        /// </summary>
        internal static string BadgeBronzeCastDescription {
            get {
                return ResourceManager.GetString("BadgeBronzeCastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Spender.
        /// </summary>
        internal static string BadgeBuyEveryItem {
            get {
                return ResourceManager.GetString("BadgeBuyEveryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy every item in the store..
        /// </summary>
        internal static string BadgeBuyEveryItemDescription {
            get {
                return ResourceManager.GetString("BadgeBuyEveryItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector.
        /// </summary>
        internal static string BadgeCatchEveryFish {
            get {
                return ResourceManager.GetString("BadgeCatchEveryFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch every type of fish..
        /// </summary>
        internal static string BadgeCatchEveryFishDescription {
            get {
                return ResourceManager.GetString("BadgeCatchEveryFishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swift Rescuer.
        /// </summary>
        internal static string BadgeFastWonGame {
            get {
                return ResourceManager.GetString("BadgeFastWonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescue the boy with {0} minutes left..
        /// </summary>
        internal static string BadgeFastWonGameDescription {
            get {
                return ResourceManager.GetString("BadgeFastWonGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongest Arm.
        /// </summary>
        internal static string BadgeGoldCast {
            get {
                return ResourceManager.GetString("BadgeGoldCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast {0} metres with the gold rod..
        /// </summary>
        internal static string BadgeGoldCastDescription {
            get {
                return ResourceManager.GetString("BadgeGoldCastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots and Lots of Money.
        /// </summary>
        internal static string BadgeLargeAccumulatedMoney {
            get {
                return ResourceManager.GetString("BadgeLargeAccumulatedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn over {0} coins..
        /// </summary>
        internal static string BadgeLargeAccumulatedMoneyDescription {
            get {
                return ResourceManager.GetString("BadgeLargeAccumulatedMoneyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stronger Arm.
        /// </summary>
        internal static string BadgeSilverCast {
            get {
                return ResourceManager.GetString("BadgeSilverCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast {0} metres with the silver rod..
        /// </summary>
        internal static string BadgeSilverCastDescription {
            get {
                return ResourceManager.GetString("BadgeSilverCastDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lots of Money.
        /// </summary>
        internal static string BadgeSmallAccumulatedMoney {
            get {
                return ResourceManager.GetString("BadgeSmallAccumulatedMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn over {0} coins..
        /// </summary>
        internal static string BadgeSmallAccumulatedMoneyDescription {
            get {
                return ResourceManager.GetString("BadgeSmallAccumulatedMoneyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Saver.
        /// </summary>
        internal static string BadgeTotalMoney {
            get {
                return ResourceManager.GetString("BadgeTotalMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have at least {0} coins at one time..
        /// </summary>
        internal static string BadgeTotalMoneyDescription {
            get {
                return ResourceManager.GetString("BadgeTotalMoneyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rescuer.
        /// </summary>
        internal static string BadgeWonGame {
            get {
                return ResourceManager.GetString("BadgeWonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully rescue the boy..
        /// </summary>
        internal static string BadgeWonGameDescription {
            get {
                return ResourceManager.GetString("BadgeWonGameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a beautiful.
        /// </summary>
        internal static string Beautiful {
            get {
                return ResourceManager.GetString("Beautiful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best yet!.
        /// </summary>
        internal static string BestDistance {
            get {
                return ResourceManager.GetString("BestDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You caught {0}!.
        /// </summary>
        internal static string Caught {
            get {
                return ResourceManager.GetString("Caught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast, reel.
        /// </summary>
        internal static string ControlsAButton {
            get {
                return ResourceManager.GetString("ControlsAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch lures.
        /// </summary>
        internal static string ControlsBButton {
            get {
                return ResourceManager.GetString("ControlsBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and Art: Daniel Cook.
        /// </summary>
        internal static string CreditsDesignArt {
            get {
                return ResourceManager.GetString("CreditsDesignArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development: Eric Woroshow.
        /// </summary>
        internal static string CreditsDevelopment {
            get {
                return ResourceManager.GetString("CreditsDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Girl is....
        /// </summary>
        internal static string CreditsTitle {
            get {
                return ResourceManager.GetString("CreditsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} metres!.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night has fallen and the boy is lost at sea..
        /// </summary>
        internal static string EndingLostText {
            get {
                return ResourceManager.GetString("EndingLostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        internal static string EndingPrompt1 {
            get {
                return ResourceManager.GetString("EndingPrompt1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to play again.
        /// </summary>
        internal static string EndingPrompt2 {
            get {
                return ResourceManager.GetString("EndingPrompt2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And they lived happily ever after!.
        /// </summary>
        internal static string EndingWinText {
            get {
                return ResourceManager.GetString("EndingWinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a fat.
        /// </summary>
        internal static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Girl.
        /// </summary>
        internal static string FishingGirl {
            get {
                return ResourceManager.GetString("FishingGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ({2}).
        /// </summary>
        internal static string FishName {
            get {
                return ResourceManager.GetString("FishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And, yes, I am quite the catch!.
        /// </summary>
        internal static string GameCaughtBoy {
            get {
                return ResourceManager.GetString("GameCaughtBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the fish have gone to sleep for the night..
        /// </summary>
        internal static string GameNoTime {
            get {
                return ResourceManager.GetString("GameNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now let go!.
        /// </summary>
        internal static string GuideCastingRelease {
            get {
                return ResourceManager.GetString("GuideCastingRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold _A_ to start casting.
        /// </summary>
        internal static string GuideCastingStart {
            get {
                return ResourceManager.GetString("GuideCastingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press _B_ to change lures.
        /// </summary>
        internal static string GuideChangeLures {
            get {
                return ResourceManager.GetString("GuideChangeLures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That fish was too big for your lure.
        /// </summary>
        internal static string GuideLureBroke {
            get {
                return ResourceManager.GetString("GuideLureBroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Medium fish to hook Large ones.
        /// </summary>
        internal static string GuideLureMediumFish {
            get {
                return ResourceManager.GetString("GuideLureMediumFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Small fish to hook Medium ones.
        /// </summary>
        internal static string GuideLureSmallFish {
            get {
                return ResourceManager.GetString("GuideLureSmallFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold _A_ to reel in your lure.
        /// </summary>
        internal static string GuideReelIn {
            get {
                return ResourceManager.GetString("GuideReelIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap _A_ to reel in large fish.
        /// </summary>
        internal static string GuideReelInLarge {
            get {
                return ResourceManager.GetString("GuideReelInLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitarfish.
        /// </summary>
        internal static string LargeCommon {
            get {
                return ResourceManager.GetString("LargeCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drumfish.
        /// </summary>
        internal static string LargeRare {
            get {
                return ResourceManager.GetString("LargeRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flutefish.
        /// </summary>
        internal static string LargeUncommon {
            get {
                return ResourceManager.GetString("LargeUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tubafish.
        /// </summary>
        internal static string LargeVeryRare {
            get {
                return ResourceManager.GetString("LargeVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablefish.
        /// </summary>
        internal static string MediumCommon {
            get {
                return ResourceManager.GetString("MediumCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskfish.
        /// </summary>
        internal static string MediumRare {
            get {
                return ResourceManager.GetString("MediumRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairfish.
        /// </summary>
        internal static string MediumUncommon {
            get {
                return ResourceManager.GetString("MediumUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lampfish.
        /// </summary>
        internal static string MediumVeryRare {
            get {
                return ResourceManager.GetString("MediumVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        internal static string MenuBadges {
            get {
                return ResourceManager.GetString("MenuBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Storage Device.
        /// </summary>
        internal static string MenuChangeStorageDevice {
            get {
                return ResourceManager.GetString("MenuChangeStorageDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string MenuControls {
            get {
                return ResourceManager.GetString("MenuControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast, reel.
        /// </summary>
        internal static string MenuControlsA {
            get {
                return ResourceManager.GetString("MenuControlsA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change lure.
        /// </summary>
        internal static string MenuControlsB {
            get {
                return ResourceManager.GetString("MenuControlsB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string MenuControlsStart {
            get {
                return ResourceManager.GetString("MenuControlsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string MenuCredits {
            get {
                return ResourceManager.GetString("MenuCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daniel Cook and Eric Woroshow.
        /// </summary>
        internal static string MenuCredits1 {
            get {
                return ResourceManager.GetString("MenuCredits1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to present FISHING GIRL with.
        /// </summary>
        internal static string MenuCredits2 {
            get {
                return ResourceManager.GetString("MenuCredits2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to freesound.org: vitriolix,.
        /// </summary>
        internal static string MenuCredits3 {
            get {
                return ResourceManager.GetString("MenuCredits3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to digifishmusic, acclivity, smcameron.
        /// </summary>
        internal static string MenuCredits4 {
            get {
                return ResourceManager.GetString("MenuCredits4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dobroide, some others.
        /// </summary>
        internal static string MenuCredits5 {
            get {
                return ResourceManager.GetString("MenuCredits5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to Dashboard.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Menu.
        /// </summary>
        internal static string MenuExitNo {
            get {
                return ResourceManager.GetString("MenuExitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit to Dashboard.
        /// </summary>
        internal static string MenuExitYes {
            get {
                return ResourceManager.GetString("MenuExitYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Options.
        /// </summary>
        internal static string MenuHelpOptions {
            get {
                return ResourceManager.GetString("MenuHelpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Play.
        /// </summary>
        internal static string MenuHowToPlay {
            get {
                return ResourceManager.GetString("MenuHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string MenuMusic {
            get {
                return ResourceManager.GetString("MenuMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string MenuOff {
            get {
                return ResourceManager.GetString("MenuOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string MenuOn {
            get {
                return ResourceManager.GetString("MenuOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Full Game.
        /// </summary>
        internal static string MenuPurchase {
            get {
                return ResourceManager.GetString("MenuPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        internal static string MenuResume {
            get {
                return ResourceManager.GetString("MenuResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string MenuSelect {
            get {
                return ResourceManager.GetString("MenuSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Effects.
        /// </summary>
        internal static string MenuSoundEffects {
            get {
                return ResourceManager.GetString("MenuSoundEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        internal static string MenuToggle {
            get {
                return ResourceManager.GetString("MenuToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration.
        /// </summary>
        internal static string MenuVibration {
            get {
                return ResourceManager.GetString("MenuVibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PurchaseFailedButton {
            get {
                return ResourceManager.GetString("PurchaseFailedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in, or you cannot purchase content..
        /// </summary>
        internal static string PurchaseFailedText {
            get {
                return ResourceManager.GetString("PurchaseFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Purchase.
        /// </summary>
        internal static string PurchaseFailedTitle {
            get {
                return ResourceManager.GetString("PurchaseFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A savefile already exists on the storage device. It will be overwritten if you continue. Is this okay?.
        /// </summary>
        internal static string SaveExists {
            get {
                return ResourceManager.GetString("SaveExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoefish.
        /// </summary>
        internal static string SmallCommon {
            get {
                return ResourceManager.GetString("SmallCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beltfish.
        /// </summary>
        internal static string SmallRare {
            get {
                return ResourceManager.GetString("SmallRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatfish.
        /// </summary>
        internal static string SmallUncommon {
            get {
                return ResourceManager.GetString("SmallUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucklefish.
        /// </summary>
        internal static string SmallVeryRare {
            get {
                return ResourceManager.GetString("SmallVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string StoreBuy {
            get {
                return ResourceManager.GetString("StoreBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string StoreClose {
            get {
                return ResourceManager.GetString("StoreClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Lure.
        /// </summary>
        internal static string StoreLureLarge {
            get {
                return ResourceManager.GetString("StoreLureLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch large fish but damage them.
        /// </summary>
        internal static string StoreLureLargeDescription {
            get {
                return ResourceManager.GetString("StoreLureLargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better Large Lure.
        /// </summary>
        internal static string StoreLureLargeUpgraded {
            get {
                return ResourceManager.GetString("StoreLureLargeUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catches large fish.
        /// </summary>
        internal static string StoreLureLargeUpgradedDescription {
            get {
                return ResourceManager.GetString("StoreLureLargeUpgradedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Lure.
        /// </summary>
        internal static string StoreLureMedium {
            get {
                return ResourceManager.GetString("StoreLureMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch medium fish.
        /// </summary>
        internal static string StoreLureMediumDescription {
            get {
                return ResourceManager.GetString("StoreLureMediumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Lure.
        /// </summary>
        internal static string StoreLureSmall {
            get {
                return ResourceManager.GetString("StoreLureSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch small fish and chain up.
        /// </summary>
        internal static string StoreLureSmallDescription {
            get {
                return ResourceManager.GetString("StoreLureSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better Small Lure.
        /// </summary>
        internal static string StoreLureSmallUpgraded {
            get {
                return ResourceManager.GetString("StoreLureSmallUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch and upgrade small fish.
        /// </summary>
        internal static string StoreLureSmallUpgradedDescription {
            get {
                return ResourceManager.GetString("StoreLureSmallUpgradedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast a short distance.
        /// </summary>
        internal static string StoreRodBronzeDescription {
            get {
                return ResourceManager.GetString("StoreRodBronzeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Rod.
        /// </summary>
        internal static string StoreRodBroze {
            get {
                return ResourceManager.GetString("StoreRodBroze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Rod.
        /// </summary>
        internal static string StoreRodGold {
            get {
                return ResourceManager.GetString("StoreRodGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast your lure farther still.
        /// </summary>
        internal static string StoreRodGoldDescription {
            get {
                return ResourceManager.GetString("StoreRodGoldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary Rod.
        /// </summary>
        internal static string StoreRodLegendary {
            get {
                return ResourceManager.GetString("StoreRodLegendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast your lure far out to sea.
        /// </summary>
        internal static string StoreRodLegendaryDescription {
            get {
                return ResourceManager.GetString("StoreRodLegendaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Rod.
        /// </summary>
        internal static string StoreRodSilver {
            get {
                return ResourceManager.GetString("StoreRodSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast your lure farther.
        /// </summary>
        internal static string StoreRodSilverDescription {
            get {
                return ResourceManager.GetString("StoreRodSilverDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a thin.
        /// </summary>
        internal static string Thin {
            get {
                return ResourceManager.GetString("Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        internal static string TitlePrompt {
            get {
                return ResourceManager.GetString("TitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Typical {
            get {
                return ResourceManager.GetString("Typical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an ugly.
        /// </summary>
        internal static string Ugly {
            get {
                return ResourceManager.GetString("Ugly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        internal static string Uncommon {
            get {
                return ResourceManager.GetString("Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t afford this yet..
        /// </summary>
        internal static string UnknownDescription {
            get {
                return ResourceManager.GetString("UnknownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string UnknownTitle {
            get {
                return ResourceManager.GetString("UnknownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect badges!.
        /// </summary>
        internal static string UpsellBadges {
            get {
                return ResourceManager.GetString("UpsellBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch larger fish!.
        /// </summary>
        internal static string UpsellFish {
            get {
                return ResourceManager.GetString("UpsellFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy bigger lures!.
        /// </summary>
        internal static string UpsellLures {
            get {
                return ResourceManager.GetString("UpsellLures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Fishing Girl and earn badges for your fishing feats!.
        /// </summary>
        internal static string UpsellMessageBadges {
            get {
                return ResourceManager.GetString("UpsellMessageBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Fishing Girl now and enjoy hours of fishing fun!.
        /// </summary>
        internal static string UpsellMessageExit {
            get {
                return ResourceManager.GetString("UpsellMessageExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Fishing Girl and get full access to the store!.
        /// </summary>
        internal static string UpsellMessageStore {
            get {
                return ResourceManager.GetString("UpsellMessageStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No time limits!.
        /// </summary>
        internal static string UpsellTime {
            get {
                return ResourceManager.GetString("UpsellTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Rare.
        /// </summary>
        internal static string VeryRare {
            get {
                return ResourceManager.GetString("VeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string VolumeHigh {
            get {
                return ResourceManager.GetString("VolumeHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string VolumeLow {
            get {
                return ResourceManager.GetString("VolumeLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string VolumeMedium {
            get {
                return ResourceManager.GetString("VolumeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string VolumeOff {
            get {
                return ResourceManager.GetString("VolumeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a young.
        /// </summary>
        internal static string Young {
            get {
                return ResourceManager.GetString("Young", resourceCulture);
            }
        }
    }
}
