//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingGirl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishingGirl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an ancient.
        /// </summary>
        public static string Ancient {
            get {
                return ResourceManager.GetString("Ancient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a beautiful.
        /// </summary>
        public static string Beautiful {
            get {
                return ResourceManager.GetString("Beautiful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best yet!.
        /// </summary>
        public static string BestDistance {
            get {
                return ResourceManager.GetString("BestDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You caught {0}!.
        /// </summary>
        public static string Caught {
            get {
                return ResourceManager.GetString("Caught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} metres!.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a fat.
        /// </summary>
        public static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Girl.
        /// </summary>
        public static string FishingGirl {
            get {
                return ResourceManager.GetString("FishingGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ({2}).
        /// </summary>
        public static string FishName {
            get {
                return ResourceManager.GetString("FishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And, yes, I am quite the catch!.
        /// </summary>
        public static string GameCaughtBoy {
            get {
                return ResourceManager.GetString("GameCaughtBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the fish have gone to sleep for the night..
        /// </summary>
        public static string GameNoTime {
            get {
                return ResourceManager.GetString("GameNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now let go!.
        /// </summary>
        public static string GuideCastingRelease {
            get {
                return ResourceManager.GetString("GuideCastingRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold _A_ to start casting.
        /// </summary>
        public static string GuideCastingStart {
            get {
                return ResourceManager.GetString("GuideCastingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string GuideCastingWait {
            get {
                return ResourceManager.GetString("GuideCastingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press _B_ to change lures.
        /// </summary>
        public static string GuideChangeLures {
            get {
                return ResourceManager.GetString("GuideChangeLures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That fish was too big for your lure.
        /// </summary>
        public static string GuideLureBroke {
            get {
                return ResourceManager.GetString("GuideLureBroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Medium fish to hook Large ones.
        /// </summary>
        public static string GuideLureMediumFish {
            get {
                return ResourceManager.GetString("GuideLureMediumFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Small fish to hook Medium ones.
        /// </summary>
        public static string GuideLureSmallFish {
            get {
                return ResourceManager.GetString("GuideLureSmallFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold _A_ to reel in your lure.
        /// </summary>
        public static string GuideReelIn {
            get {
                return ResourceManager.GetString("GuideReelIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitarfish.
        /// </summary>
        public static string LargeCommon {
            get {
                return ResourceManager.GetString("LargeCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drumfish.
        /// </summary>
        public static string LargeRare {
            get {
                return ResourceManager.GetString("LargeRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flutefish.
        /// </summary>
        public static string LargeUncommon {
            get {
                return ResourceManager.GetString("LargeUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tubafish.
        /// </summary>
        public static string LargeVeryRare {
            get {
                return ResourceManager.GetString("LargeVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb Lure.
        /// </summary>
        public static string LureBomb {
            get {
                return ResourceManager.GetString("LureBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explodes the first fish it touches..
        /// </summary>
        public static string LureBombDescription {
            get {
                return ResourceManager.GetString("LureBombDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Lure.
        /// </summary>
        public static string LureLarge {
            get {
                return ResourceManager.GetString("LureLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you catch Large sized fish..
        /// </summary>
        public static string LureLargeDescription {
            get {
                return ResourceManager.GetString("LureLargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Lure.
        /// </summary>
        public static string LureMedium {
            get {
                return ResourceManager.GetString("LureMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you catch Medium sized fish..
        /// </summary>
        public static string LureMediumDescription {
            get {
                return ResourceManager.GetString("LureMediumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Lure.
        /// </summary>
        public static string LureSmall {
            get {
                return ResourceManager.GetString("LureSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you catch Small sized fish..
        /// </summary>
        public static string LureSmallDescription {
            get {
                return ResourceManager.GetString("LureSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablefish.
        /// </summary>
        public static string MediumCommon {
            get {
                return ResourceManager.GetString("MediumCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskfish.
        /// </summary>
        public static string MediumRare {
            get {
                return ResourceManager.GetString("MediumRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairfish.
        /// </summary>
        public static string MediumUncommon {
            get {
                return ResourceManager.GetString("MediumUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lampfish.
        /// </summary>
        public static string MediumVeryRare {
            get {
                return ResourceManager.GetString("MediumVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        public static string MenuBadges {
            get {
                return ResourceManager.GetString("MenuBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string MenuControls {
            get {
                return ResourceManager.GetString("MenuControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string MenuCredits {
            get {
                return ResourceManager.GetString("MenuCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Community Games.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp; Options.
        /// </summary>
        public static string MenuHelpOptions {
            get {
                return ResourceManager.GetString("MenuHelpOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How To Play.
        /// </summary>
        public static string MenuHowToPlay {
            get {
                return ResourceManager.GetString("MenuHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Full Game.
        /// </summary>
        public static string MenuPurchase {
            get {
                return ResourceManager.GetString("MenuPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        public static string MenuResume {
            get {
                return ResourceManager.GetString("MenuResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string MenuSelect {
            get {
                return ResourceManager.GetString("MenuSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string MenuVolume {
            get {
                return ResourceManager.GetString("MenuVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        public static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you cast a short distance..
        /// </summary>
        public static string RodBronzeDescription {
            get {
                return ResourceManager.GetString("RodBronzeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Rod.
        /// </summary>
        public static string RodBroze {
            get {
                return ResourceManager.GetString("RodBroze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Rod.
        /// </summary>
        public static string RodGold {
            get {
                return ResourceManager.GetString("RodGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you cast your lure farther still..
        /// </summary>
        public static string RodGoldDescription {
            get {
                return ResourceManager.GetString("RodGoldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary Rod.
        /// </summary>
        public static string RodLegendary {
            get {
                return ResourceManager.GetString("RodLegendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you cast your lure to the far shore..
        /// </summary>
        public static string RodLegendaryDescription {
            get {
                return ResourceManager.GetString("RodLegendaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Rod.
        /// </summary>
        public static string RodSilver {
            get {
                return ResourceManager.GetString("RodSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you cast your lure farther..
        /// </summary>
        public static string RodSilverDescription {
            get {
                return ResourceManager.GetString("RodSilverDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoefish.
        /// </summary>
        public static string SmallCommon {
            get {
                return ResourceManager.GetString("SmallCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beltfish.
        /// </summary>
        public static string SmallRare {
            get {
                return ResourceManager.GetString("SmallRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatfish.
        /// </summary>
        public static string SmallUncommon {
            get {
                return ResourceManager.GetString("SmallUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucklefish.
        /// </summary>
        public static string SmallVeryRare {
            get {
                return ResourceManager.GetString("SmallVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a thin.
        /// </summary>
        public static string Thin {
            get {
                return ResourceManager.GetString("Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        public static string TitlePrompt {
            get {
                return ResourceManager.GetString("TitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        public static string Typical {
            get {
                return ResourceManager.GetString("Typical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an ugly.
        /// </summary>
        public static string Ugly {
            get {
                return ResourceManager.GetString("Ugly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        public static string Uncommon {
            get {
                return ResourceManager.GetString("Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t afford this yet..
        /// </summary>
        public static string UnknownDescription {
            get {
                return ResourceManager.GetString("UnknownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        public static string UnknownTitle {
            get {
                return ResourceManager.GetString("UnknownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Rare.
        /// </summary>
        public static string VeryRare {
            get {
                return ResourceManager.GetString("VeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a young.
        /// </summary>
        public static string Young {
            get {
                return ResourceManager.GetString("Young", resourceCulture);
            }
        }
    }
}
