//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishingGirl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishingGirl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an ancient.
        /// </summary>
        internal static string Ancient {
            get {
                return ResourceManager.GetString("Ancient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a beautiful.
        /// </summary>
        internal static string Beautiful {
            get {
                return ResourceManager.GetString("Beautiful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best yet!.
        /// </summary>
        internal static string BestDistance {
            get {
                return ResourceManager.GetString("BestDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You caught {0}!.
        /// </summary>
        internal static string Caught {
            get {
                return ResourceManager.GetString("Caught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast, reel.
        /// </summary>
        internal static string ControlsAButton {
            get {
                return ResourceManager.GetString("ControlsAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch lures.
        /// </summary>
        internal static string ControlsBButton {
            get {
                return ResourceManager.GetString("ControlsBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design and Art: Daniel Cook.
        /// </summary>
        internal static string CreditsDesignArt {
            get {
                return ResourceManager.GetString("CreditsDesignArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development: Eric Woroshow.
        /// </summary>
        internal static string CreditsDevelopment {
            get {
                return ResourceManager.GetString("CreditsDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Girl is....
        /// </summary>
        internal static string CreditsTitle {
            get {
                return ResourceManager.GetString("CreditsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} metres!.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a fat.
        /// </summary>
        internal static string Fat {
            get {
                return ResourceManager.GetString("Fat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Girl.
        /// </summary>
        internal static string FishingGirl {
            get {
                return ResourceManager.GetString("FishingGirl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ({2}).
        /// </summary>
        internal static string FishName {
            get {
                return ResourceManager.GetString("FishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And, yes, I am quite the catch!.
        /// </summary>
        internal static string GameCaughtBoy {
            get {
                return ResourceManager.GetString("GameCaughtBoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the fish have gone to sleep for the night..
        /// </summary>
        internal static string GameNoTime {
            get {
                return ResourceManager.GetString("GameNoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now let go!.
        /// </summary>
        internal static string GuideCastingRelease {
            get {
                return ResourceManager.GetString("GuideCastingRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold _A_ to start casting.
        /// </summary>
        internal static string GuideCastingStart {
            get {
                return ResourceManager.GetString("GuideCastingStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string GuideCastingWait {
            get {
                return ResourceManager.GetString("GuideCastingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press _B_ to change lures.
        /// </summary>
        internal static string GuideChangeLures {
            get {
                return ResourceManager.GetString("GuideChangeLures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That fish was too big for your lure.
        /// </summary>
        internal static string GuideLureBroke {
            get {
                return ResourceManager.GetString("GuideLureBroke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Medium fish to hook Large ones.
        /// </summary>
        internal static string GuideLureMediumFish {
            get {
                return ResourceManager.GetString("GuideLureMediumFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Small fish to hook Medium ones.
        /// </summary>
        internal static string GuideLureSmallFish {
            get {
                return ResourceManager.GetString("GuideLureSmallFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold _A_ to reel in your lure.
        /// </summary>
        internal static string GuideReelIn {
            get {
                return ResourceManager.GetString("GuideReelIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guitarfish.
        /// </summary>
        internal static string LargeCommon {
            get {
                return ResourceManager.GetString("LargeCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drumfish.
        /// </summary>
        internal static string LargeRare {
            get {
                return ResourceManager.GetString("LargeRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flutefish.
        /// </summary>
        internal static string LargeUncommon {
            get {
                return ResourceManager.GetString("LargeUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tubafish.
        /// </summary>
        internal static string LargeVeryRare {
            get {
                return ResourceManager.GetString("LargeVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bomb Lure.
        /// </summary>
        internal static string LureBomb {
            get {
                return ResourceManager.GetString("LureBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explodes the first fish it touches..
        /// </summary>
        internal static string LureBombDescription {
            get {
                return ResourceManager.GetString("LureBombDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large Lure.
        /// </summary>
        internal static string LureLarge {
            get {
                return ResourceManager.GetString("LureLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you catch Large sized fish..
        /// </summary>
        internal static string LureLargeDescription {
            get {
                return ResourceManager.GetString("LureLargeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Lure.
        /// </summary>
        internal static string LureMedium {
            get {
                return ResourceManager.GetString("LureMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you catch Medium sized fish..
        /// </summary>
        internal static string LureMediumDescription {
            get {
                return ResourceManager.GetString("LureMediumDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Lure.
        /// </summary>
        internal static string LureSmall {
            get {
                return ResourceManager.GetString("LureSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you catch Small sized fish..
        /// </summary>
        internal static string LureSmallDescription {
            get {
                return ResourceManager.GetString("LureSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablefish.
        /// </summary>
        internal static string MediumCommon {
            get {
                return ResourceManager.GetString("MediumCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deskfish.
        /// </summary>
        internal static string MediumRare {
            get {
                return ResourceManager.GetString("MediumRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chairfish.
        /// </summary>
        internal static string MediumUncommon {
            get {
                return ResourceManager.GetString("MediumUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lampfish.
        /// </summary>
        internal static string MediumVeryRare {
            get {
                return ResourceManager.GetString("MediumVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MenuBack {
            get {
                return ResourceManager.GetString("MenuBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        internal static string MenuBadges {
            get {
                return ResourceManager.GetString("MenuBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Dashboard.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Main Menu.
        /// </summary>
        internal static string MenuExitNo {
            get {
                return ResourceManager.GetString("MenuExitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Dashboard.
        /// </summary>
        internal static string MenuExitYes {
            get {
                return ResourceManager.GetString("MenuExitYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Full Game.
        /// </summary>
        internal static string MenuPurchase {
            get {
                return ResourceManager.GetString("MenuPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        internal static string MenuResume {
            get {
                return ResourceManager.GetString("MenuResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string MenuSelect {
            get {
                return ResourceManager.GetString("MenuSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect badges!.
        /// </summary>
        internal static string NagBadges {
            get {
                return ResourceManager.GetString("NagBadges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Fishing Girl now and enjoy hours of fishing fun!.
        /// </summary>
        internal static string NagBubble {
            get {
                return ResourceManager.GetString("NagBubble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch larger fish!.
        /// </summary>
        internal static string NagFish {
            get {
                return ResourceManager.GetString("NagFish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy bigger lures!.
        /// </summary>
        internal static string NagLures {
            get {
                return ResourceManager.GetString("NagLures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No time limits!.
        /// </summary>
        internal static string NagTime {
            get {
                return ResourceManager.GetString("NagTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string PurchaseFailedButton {
            get {
                return ResourceManager.GetString("PurchaseFailedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not signed in, or you cannot purchase content..
        /// </summary>
        internal static string PurchaseFailedText {
            get {
                return ResourceManager.GetString("PurchaseFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Purchase.
        /// </summary>
        internal static string PurchaseFailedTitle {
            get {
                return ResourceManager.GetString("PurchaseFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rare.
        /// </summary>
        internal static string Rare {
            get {
                return ResourceManager.GetString("Rare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you cast a short distance..
        /// </summary>
        internal static string RodBronzeDescription {
            get {
                return ResourceManager.GetString("RodBronzeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze Rod.
        /// </summary>
        internal static string RodBroze {
            get {
                return ResourceManager.GetString("RodBroze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold Rod.
        /// </summary>
        internal static string RodGold {
            get {
                return ResourceManager.GetString("RodGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you cast your lure farther still..
        /// </summary>
        internal static string RodGoldDescription {
            get {
                return ResourceManager.GetString("RodGoldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary Rod.
        /// </summary>
        internal static string RodLegendary {
            get {
                return ResourceManager.GetString("RodLegendary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you cast your lure to the far shore..
        /// </summary>
        internal static string RodLegendaryDescription {
            get {
                return ResourceManager.GetString("RodLegendaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver Rod.
        /// </summary>
        internal static string RodSilver {
            get {
                return ResourceManager.GetString("RodSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets you cast your lure farther..
        /// </summary>
        internal static string RodSilverDescription {
            get {
                return ResourceManager.GetString("RodSilverDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoefish.
        /// </summary>
        internal static string SmallCommon {
            get {
                return ResourceManager.GetString("SmallCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beltfish.
        /// </summary>
        internal static string SmallRare {
            get {
                return ResourceManager.GetString("SmallRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatfish.
        /// </summary>
        internal static string SmallUncommon {
            get {
                return ResourceManager.GetString("SmallUncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucklefish.
        /// </summary>
        internal static string SmallVeryRare {
            get {
                return ResourceManager.GetString("SmallVeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a thin.
        /// </summary>
        internal static string Thin {
            get {
                return ResourceManager.GetString("Thin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press.
        /// </summary>
        internal static string TitlePrompt {
            get {
                return ResourceManager.GetString("TitlePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string Typical {
            get {
                return ResourceManager.GetString("Typical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an ugly.
        /// </summary>
        internal static string Ugly {
            get {
                return ResourceManager.GetString("Ugly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncommon.
        /// </summary>
        internal static string Uncommon {
            get {
                return ResourceManager.GetString("Uncommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t afford this yet..
        /// </summary>
        internal static string UnknownDescription {
            get {
                return ResourceManager.GetString("UnknownDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ???.
        /// </summary>
        internal static string UnknownTitle {
            get {
                return ResourceManager.GetString("UnknownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Rare.
        /// </summary>
        internal static string VeryRare {
            get {
                return ResourceManager.GetString("VeryRare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string VolumeHigh {
            get {
                return ResourceManager.GetString("VolumeHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string VolumeLow {
            get {
                return ResourceManager.GetString("VolumeLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string VolumeMedium {
            get {
                return ResourceManager.GetString("VolumeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string VolumeOff {
            get {
                return ResourceManager.GetString("VolumeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a young.
        /// </summary>
        internal static string Young {
            get {
                return ResourceManager.GetString("Young", resourceCulture);
            }
        }
    }
}
